### ISSUE TITLE
Ad dthe ability to do this with settings?

### ISSUE THREAD

**Issue by abuxton** [GeoffWilliams/puppet_dump#1]
I have out of band been working on a function to make this do the same thing with setting. i.e 
require 'puppet'
2.0.0-p353 :002 > Puppet::Settings.new.each {|x| puts x}

Seems you have the module, and as a seperate function or combined optional var of teh function this could also be useful.

**Comment by GeoffWilliams** [comment]
@abuxton  I tried this today with an inline template and wasn't able to get any output:

``` puppet
$a = inline_template("<%= settings = {} ; Puppet::Settings.new.each { |v| settings[v] = v } ; settings.to_yaml %>")
notify { "x":
  message => $a,
}
```

Would a resource that wraps `puppet config print` do it for you?

**Comment by GeoffWilliams** [comment]
@abuxton does puppet_dump::config{"foo":} do what you want? -- it runs `puppet config print` inside a notify using `inline_template` :D

**Comment by GeoffWilliams** [comment]
...no, it does not - I need settings from the live agent too now ;-)

Fixed: Added `puppet_dump::settings` and also the ability to save captured settings to a file on the host in `0.4.1`
